# Generated by Django 4.1.3 on 2023-01-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_resgisteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_first_name', models.CharField(max_length=30)),
                ('user_last_name', models.CharField(max_length=30)),
                ('user_age', models.CharField(max_length=3)),
                ('user_phone', models.CharField(max_length=15)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_address', models.TextField()),
                ('user_city', models.CharField(max_length=15)),
                ('user_freelancer', models.BooleanField()),
                ('user_bio', models.TextField(max_length=255)),
                ('user_profile_picture', models.ImageField(default=None, upload_to='image/')),
                ('user_webstie', models.URLField()),
                ('user_password', models.CharField(max_length=8)),
                ('user_conf_password', models.CharField(max_length=8)),
            ],
        ),
    ]
