# Generated by Django 4.1.3 on 2023-02-17 06:33

from django.db import migrations, models
import django.db.models.manager
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('city', models.CharField(max_length=30, null=True)),
                ('country', models.CharField(max_length=30, null=True)),
                ('login_check', models.BooleanField(blank=True)),
                ('user_first_name', models.CharField(max_length=30, null=True)),
                ('user_last_name', models.CharField(max_length=30, null=True)),
                ('user_age', models.IntegerField(null=True)),
                ('user_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('user_email', models.EmailField(max_length=254, null=True)),
                ('user_address', models.TextField(null=True)),
                ('user_city', models.CharField(max_length=15, null=True)),
                ('user_freelancer', models.BooleanField(blank=True)),
                ('user_bio', models.TextField(max_length=255, null=True)),
                ('user_profile_picture', models.ImageField(default=None, upload_to='image/%y')),
                ('user_website', models.URLField()),
                ('user_password', models.CharField(max_length=9, null=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('registration', django.db.models.manager.Manager()),
            ],
        ),
    ]
