# Generated by Django 4.1.3 on 2023-02-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_Auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_register',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
