# Generated by Django 4.1.3 on 2023-01-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_Auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_resgisteration',
            name='user_age',
            field=models.IntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name='user_resgisteration',
            name='user_phone',
            field=models.IntegerField(max_length=15),
        ),
    ]
