# Generated by Django 4.1.3 on 2023-02-17 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_Auth', '0002_alter_user_register_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_register',
            name='login_check',
        ),
    ]
