# Generated by Django 4.1.3 on 2023-01-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_Auth', '0002_alter_user_resgisteration_user_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_resgisteration',
            name='user_profile_picture',
            field=models.ImageField(default=None, upload_to='image/%y'),
        ),
    ]
