# Generated by Django 4.1.3 on 2023-01-24 08:02

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user_Auth', '0003_alter_user_resgisteration_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_resgisteration',
            name='user_address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user_resgisteration',
            name='user_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_resgisteration',
            name='user_bio',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user_resgisteration',
            name='user_city',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user_resgisteration',
            name='user_conf_password',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='user_resgisteration',
            name='user_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user_resgisteration',
            name='user_first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user_resgisteration',
            name='user_last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user_resgisteration',
            name='user_password',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='user_resgisteration',
            name='user_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
