# Generated by Django 4.1.3 on 2023-02-17 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_Auth', '0003_remove_user_register_login_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_register',
            name='user_city',
        ),
    ]
