# Generated by Django 4.1.3 on 2023-02-17 15:00

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('user_Auth', '0004_remove_user_register_user_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.CharField(max_length=30, null=True)),
                ('country', models.CharField(max_length=30, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('Name_of_degree', models.CharField(max_length=30, null=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('education_obj', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='professional_experiance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.CharField(max_length=30, null=True)),
                ('country', models.CharField(max_length=30, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('Company_name', models.CharField(max_length=30, null=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('prof_exp_obj', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='user_register',
            managers=[
                ('registration_obj', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=30, null=True)),
                ('grip_value', models.SmallIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('user_skills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_Auth.user_register', verbose_name='User_id')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('Skill_obj', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='professionl_achivements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achivements_name', models.CharField(max_length=30)),
                ('certification_link', models.URLField(null=True)),
                ('certification_start_date', models.DateField(null=True)),
                ('certification_end_date', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('p_achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_Auth.professional_experiance', verbose_name='p_exp_id')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('p_achievements_obj', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='professional_experiance',
            name='user_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_Auth.user_register', verbose_name='User_id'),
        ),
        migrations.CreateModel(
            name='Educative_achivements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achivements_name', models.CharField(max_length=30)),
                ('certification_link', models.URLField(null=True)),
                ('certification_start_date', models.DateField(null=True)),
                ('certification_end_date', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_Auth.education', verbose_name='education_id')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('edu_achivements_obj', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='education',
            name='user_education',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_Auth.user_register', verbose_name='USER_ID'),
        ),
        migrations.CreateModel(
            name='Company_skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=30, null=True)),
                ('grip_value', models.SmallIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('p_skills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_Auth.professional_experiance', verbose_name='Prof_exp_id')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('prof_skill_obj', django.db.models.manager.Manager()),
            ],
        ),
    ]
