# Generated by Django 4.1.3 on 2023-02-07 21:49

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user_Auth', '0004_alter_user_resgisteration_user_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_first_name', models.CharField(max_length=30, null=True)),
                ('user_last_name', models.CharField(max_length=30, null=True)),
                ('user_age', models.IntegerField(null=True)),
                ('user_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('user_email', models.EmailField(max_length=254, null=True)),
                ('user_address', models.TextField(null=True)),
                ('user_city', models.CharField(max_length=15, null=True)),
                ('user_freelancer', models.BooleanField()),
                ('user_bio', models.TextField(max_length=255, null=True)),
                ('user_profile_picture', models.ImageField(default=None, upload_to='image/%y')),
                ('user_webstie', models.URLField()),
                ('user_password', models.CharField(max_length=9)),
                ('user_conf_password', models.CharField(max_length=9)),
            ],
        ),
        migrations.DeleteModel(
            name='user_resgisteration',
        ),
    ]
