# Generated by Django 4.1.3 on 2023-02-08 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_Auth', '0006_remove_user_register_user_conf_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_register',
            old_name='user_webstie',
            new_name='user_website',
        ),
    ]
